### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by walseb**
I was kinda confused by this since there doesn't seem to be a `un-SN` type. But maybe it's correct though, I haven't fully understood this library yet. Oh and thanks for creating this library!

### CODE REVIEW

**Comment by turion** [comment]
Thanks :) do feel free to ask questions! Did you read the article, was it any help?

**Comment by walseb** [comment]
Ok cool! Yeah it's great especially as kind of a dictionary since the haddocks are rough if you don't know what the building blocks are (like CLSFs, time domains, etc). But it's still a lot to take in compared to yampa. Right now I'm just going through the haddocks and trying to understand how the operators work

**Comment by turion** [comment]
It's good to know what about the library is hard to understand. I guess what's lacking is a long tutorial, but I couldn't find the time for that amongst all my other projects. You can also have a look at https://github.com/turion/sonnendemo, that might give you a flavour of how to use what operator.

**Comment by walseb** [comment]
I think the largest problem for me is just the sheer amount of operators and functions rhine introduces and understanding how they work. I think a cheat sheet where each operator/function is described with a sentence or so would be very useful. Maybe I will try to write one once I get a better understanding. Thanks I will look into that!

**Comment by turion** [comment]
Oh a cheat sheet is an excellent idea. I didn't think about that. I made one today:

https://github.com/turion/rhine/blob/master/CHEATSHEET.md

**Comment by walseb** [comment]
Oh wow nice! It seems only to exist on the master branch right now though

**Pull request merged**
